version: "3"
services:
  relational_business_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - "./docker/db:/var/lib/mysql"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    command: mysqld --max_allowed_packet=128M --sql-mode=""
